// <auto-generated />
using System;
using AarhusSpaceProgram.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AarhusSpaceProgram.Api.Migrations
{
    [DbContext(typeof(SpaceProgramContext))]
    [Migration("20260427100313_0004-UpdatedSeedData")]
    partial class _0004UpdatedSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.CelestialBody", b =>
                {
                    b.Property<int>("BodyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("body_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BodyId"));

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("body_type");

                    b.Property<int>("Distance")
                        .HasColumnType("int")
                        .HasColumnName("Distance");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentBodyId")
                        .HasColumnType("int")
                        .HasColumnName("parent_body_id");

                    b.Property<string>("Subtype")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("subtype");

                    b.HasKey("BodyId");

                    b.HasIndex("ParentBodyId");

                    b.ToTable("CelestialBody");
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("hire_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("EmployeeId");

                    b.HasIndex("AppUserId");

                    b.ToTable("Employee");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.Experiment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("experiment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("creation_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("description");

                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("ScientistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("ScientistId");

                    b.ToTable("Experiments");
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.LaunchPad", b =>
                {
                    b.Property<int>("LaunchPadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("launchpad_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LaunchPadId"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("location");

                    b.Property<double>("MaxWeight")
                        .HasColumnType("float")
                        .HasColumnName("max_supported_weight");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("LaunchPadId");

                    b.ToTable("LaunchPad");
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.Mission", b =>
                {
                    b.Property<int>("MissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mission_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MissionId"));

                    b.Property<int>("LaunchPadId")
                        .HasColumnType("int")
                        .HasColumnName("launchpad_id");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("manager_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("PlannedDuration")
                        .HasColumnType("int")
                        .HasColumnName("planned_duration");

                    b.Property<DateOnly>("PlannedLaunchDate")
                        .HasColumnType("date")
                        .HasColumnName("planned_launch_date");

                    b.Property<int>("RocketId")
                        .HasColumnType("int")
                        .HasColumnName("rocket_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<int>("TargetBodyId")
                        .HasColumnType("int")
                        .HasColumnName("target_body_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.HasKey("MissionId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("RocketId")
                        .IsUnique();

                    b.HasIndex("TargetBodyId");

                    b.HasIndex("LaunchPadId", "PlannedLaunchDate")
                        .IsUnique();

                    b.ToTable("Mission");
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.Rocket", b =>
                {
                    b.Property<int>("RocketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rocket_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RocketId"));

                    b.Property<int>("CrewCap")
                        .HasColumnType("int")
                        .HasColumnName("crew_cap");

                    b.Property<int>("FuelCap")
                        .HasColumnType("int")
                        .HasColumnName("fuel_cap");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("model_name");

                    b.Property<int>("NoOfStages")
                        .HasColumnType("int")
                        .HasColumnName("no_of_stages");

                    b.Property<int>("PayloadCap")
                        .HasColumnType("int")
                        .HasColumnName("payload_cap");

                    b.Property<double>("Weight")
                        .HasColumnType("float")
                        .HasColumnName("weight");

                    b.HasKey("RocketId");

                    b.ToTable("Rocket", t =>
                        {
                            t.HasCheckConstraint("CK_Rocket_Weight", "weight >= 0 ");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Mission_Astronaut", b =>
                {
                    b.Property<int>("AstronautEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.HasKey("AstronautEmployeeId", "MissionId");

                    b.HasIndex("MissionId");

                    b.ToTable("Mission_Astronaut");
                });

            modelBuilder.Entity("Mission_Scientist", b =>
                {
                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<int>("ScientistEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("MissionId", "ScientistEmployeeId");

                    b.HasIndex("ScientistEmployeeId");

                    b.ToTable("Mission_Scientist");
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.Astronaut", b =>
                {
                    b.HasBaseType("AarhusSpaceProgram.Api.Entities.Employee");

                    b.Property<int>("HoursInSimulation")
                        .HasColumnType("int")
                        .HasColumnName("hours_in_sim");

                    b.Property<int>("HoursInSpace")
                        .HasColumnType("int")
                        .HasColumnName("hours_in_space");

                    b.Property<string>("Paygrade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("paygrade");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("rank");

                    b.ToTable("Astronaut");
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.Manager", b =>
                {
                    b.HasBaseType("AarhusSpaceProgram.Api.Entities.Employee");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("department");

                    b.ToTable("Manager");
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.Scientist", b =>
                {
                    b.HasBaseType("AarhusSpaceProgram.Api.Entities.Employee");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("speciality");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title");

                    b.ToTable("Scientist");
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.CelestialBody", b =>
                {
                    b.HasOne("AarhusSpaceProgram.Api.Entities.CelestialBody", "ParentBody")
                        .WithMany()
                        .HasForeignKey("ParentBodyId");

                    b.Navigation("ParentBody");
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.Employee", b =>
                {
                    b.HasOne("AarhusSpaceProgram.Api.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.Experiment", b =>
                {
                    b.HasOne("AarhusSpaceProgram.Api.Entities.Mission", "Mission")
                        .WithMany("Experiments")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AarhusSpaceProgram.Api.Entities.Scientist", "Scientist")
                        .WithMany("Experiments")
                        .HasForeignKey("ScientistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Scientist");
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.Mission", b =>
                {
                    b.HasOne("AarhusSpaceProgram.Api.Entities.LaunchPad", "LaunchPad")
                        .WithMany("Missions")
                        .HasForeignKey("LaunchPadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AarhusSpaceProgram.Api.Entities.Manager", "Manager")
                        .WithMany("ManagedMissions")
                        .HasForeignKey("ManagerId");

                    b.HasOne("AarhusSpaceProgram.Api.Entities.Rocket", "Rocket")
                        .WithOne("Mission")
                        .HasForeignKey("AarhusSpaceProgram.Api.Entities.Mission", "RocketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AarhusSpaceProgram.Api.Entities.CelestialBody", "TargetBody")
                        .WithMany("TargetMissions")
                        .HasForeignKey("TargetBodyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LaunchPad");

                    b.Navigation("Manager");

                    b.Navigation("Rocket");

                    b.Navigation("TargetBody");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AarhusSpaceProgram.Api.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AarhusSpaceProgram.Api.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AarhusSpaceProgram.Api.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AarhusSpaceProgram.Api.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mission_Astronaut", b =>
                {
                    b.HasOne("AarhusSpaceProgram.Api.Entities.Astronaut", null)
                        .WithMany()
                        .HasForeignKey("AstronautEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AarhusSpaceProgram.Api.Entities.Mission", null)
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Mission_Scientist", b =>
                {
                    b.HasOne("AarhusSpaceProgram.Api.Entities.Mission", null)
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AarhusSpaceProgram.Api.Entities.Scientist", null)
                        .WithMany()
                        .HasForeignKey("ScientistEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.Astronaut", b =>
                {
                    b.HasOne("AarhusSpaceProgram.Api.Entities.Employee", null)
                        .WithOne()
                        .HasForeignKey("AarhusSpaceProgram.Api.Entities.Astronaut", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.Manager", b =>
                {
                    b.HasOne("AarhusSpaceProgram.Api.Entities.Employee", null)
                        .WithOne()
                        .HasForeignKey("AarhusSpaceProgram.Api.Entities.Manager", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.Scientist", b =>
                {
                    b.HasOne("AarhusSpaceProgram.Api.Entities.Employee", null)
                        .WithOne()
                        .HasForeignKey("AarhusSpaceProgram.Api.Entities.Scientist", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.CelestialBody", b =>
                {
                    b.Navigation("TargetMissions");
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.LaunchPad", b =>
                {
                    b.Navigation("Missions");
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.Mission", b =>
                {
                    b.Navigation("Experiments");
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.Rocket", b =>
                {
                    b.Navigation("Mission");
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.Manager", b =>
                {
                    b.Navigation("ManagedMissions");
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.Scientist", b =>
                {
                    b.Navigation("Experiments");
                });
#pragma warning restore 612, 618
        }
    }
}
