// <auto-generated />
using System;
using AarhusSpaceProgram.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AarhusSpaceProgram.Api.Migrations
{
    [DbContext(typeof(SpaceProgramContext))]
    [Migration("20260325094753_0001-InitialCreate")]
    partial class _0001InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.CelestialBody", b =>
                {
                    b.Property<int>("BodyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("body_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BodyId"));

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("body_type");

                    b.Property<int>("Distance")
                        .HasColumnType("int")
                        .HasColumnName("Distance");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentBodyId")
                        .HasColumnType("int")
                        .HasColumnName("parent_body_id");

                    b.Property<string>("Subtype")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("subtype");

                    b.HasKey("BodyId");

                    b.HasIndex("ParentBodyId");

                    b.ToTable("CelestialBody");

                    b.HasData(
                        new
                        {
                            BodyId = 1,
                            BodyType = "Planet",
                            Distance = 0,
                            Name = "Earth",
                            Subtype = "RockyPlanet"
                        },
                        new
                        {
                            BodyId = 2,
                            BodyType = "Moon",
                            Distance = 384400,
                            Name = "Moon",
                            ParentBodyId = 1,
                            Subtype = "None"
                        },
                        new
                        {
                            BodyId = 3,
                            BodyType = "Planet",
                            Distance = 225000000,
                            Name = "Mars",
                            Subtype = "RockyPlanet"
                        });
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("hire_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employee");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.LaunchPad", b =>
                {
                    b.Property<int>("LaunchPadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("launchpad_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LaunchPadId"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("location");

                    b.Property<double>("MaxWeight")
                        .HasColumnType("float")
                        .HasColumnName("max_supported_weight");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("LaunchPadId");

                    b.ToTable("LaunchPad");

                    b.HasData(
                        new
                        {
                            LaunchPadId = 1,
                            Location = "Hogwartz",
                            MaxWeight = 3000000.0,
                            Status = "Active"
                        },
                        new
                        {
                            LaunchPadId = 2,
                            Location = "The forbidden forest",
                            MaxWeight = 4000000.0,
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.Mission", b =>
                {
                    b.Property<int>("MissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mission_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MissionId"));

                    b.Property<int>("LaunchPadId")
                        .HasColumnType("int")
                        .HasColumnName("launchpad_id");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("manager_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("PlannedDuration")
                        .HasColumnType("int")
                        .HasColumnName("planned_duration");

                    b.Property<DateOnly>("PlannedLaunchDate")
                        .HasColumnType("date")
                        .HasColumnName("planned_launch_date");

                    b.Property<int>("RocketId")
                        .HasColumnType("int")
                        .HasColumnName("rocket_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<int>("TargetBodyId")
                        .HasColumnType("int")
                        .HasColumnName("target_body_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.HasKey("MissionId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("RocketId")
                        .IsUnique();

                    b.HasIndex("TargetBodyId");

                    b.HasIndex("LaunchPadId", "PlannedLaunchDate")
                        .IsUnique();

                    b.ToTable("Mission");

                    b.HasData(
                        new
                        {
                            MissionId = 1,
                            LaunchPadId = 1,
                            ManagerId = 1,
                            Name = "Apollo 11",
                            PlannedDuration = 8,
                            PlannedLaunchDate = new DateOnly(2010, 7, 16),
                            RocketId = 1,
                            Status = "Completed",
                            TargetBodyId = 1,
                            Type = "Landing"
                        },
                        new
                        {
                            MissionId = 2,
                            LaunchPadId = 2,
                            ManagerId = 2,
                            Name = "Artemis I",
                            PlannedDuration = 25,
                            PlannedLaunchDate = new DateOnly(2025, 11, 16),
                            RocketId = 2,
                            Status = "Active",
                            TargetBodyId = 2,
                            Type = "Orbiting"
                        });
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.Rocket", b =>
                {
                    b.Property<int>("RocketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rocket_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RocketId"));

                    b.Property<int>("CrewCap")
                        .HasColumnType("int")
                        .HasColumnName("crew_cap");

                    b.Property<int>("FuelCap")
                        .HasColumnType("int")
                        .HasColumnName("fuel_cap");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("model_name");

                    b.Property<int>("NoOfStages")
                        .HasColumnType("int")
                        .HasColumnName("no_of_stages");

                    b.Property<int>("PayloadCap")
                        .HasColumnType("int")
                        .HasColumnName("payload_cap");

                    b.Property<double>("Weight")
                        .HasColumnType("float")
                        .HasColumnName("weight");

                    b.HasKey("RocketId");

                    b.ToTable("Rocket", t =>
                        {
                            t.HasCheckConstraint("CK_Rocket_Weight", "weight >= 0 ");
                        });

                    b.HasData(
                        new
                        {
                            RocketId = 1,
                            CrewCap = 3,
                            FuelCap = 200000,
                            ModelName = "Superfly",
                            NoOfStages = 3,
                            PayloadCap = 14000,
                            Weight = 296000.0
                        },
                        new
                        {
                            RocketId = 2,
                            CrewCap = 2,
                            FuelCap = 150000,
                            ModelName = "BC Rocket",
                            NoOfStages = 2,
                            PayloadCap = 13000,
                            Weight = 230000.0
                        });
                });

            modelBuilder.Entity("Mission_Astronaut", b =>
                {
                    b.Property<int>("AstronautEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.HasKey("AstronautEmployeeId", "MissionId");

                    b.HasIndex("MissionId");

                    b.ToTable("Mission_Astronaut");

                    b.HasData(
                        new
                        {
                            AstronautEmployeeId = 5,
                            MissionId = 1
                        },
                        new
                        {
                            AstronautEmployeeId = 6,
                            MissionId = 1
                        },
                        new
                        {
                            AstronautEmployeeId = 7,
                            MissionId = 1
                        },
                        new
                        {
                            AstronautEmployeeId = 6,
                            MissionId = 2
                        },
                        new
                        {
                            AstronautEmployeeId = 7,
                            MissionId = 2
                        });
                });

            modelBuilder.Entity("Mission_Scientist", b =>
                {
                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<int>("ScientistEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("MissionId", "ScientistEmployeeId");

                    b.HasIndex("ScientistEmployeeId");

                    b.ToTable("Mission_Scientist");

                    b.HasData(
                        new
                        {
                            MissionId = 1,
                            ScientistEmployeeId = 3
                        },
                        new
                        {
                            MissionId = 1,
                            ScientistEmployeeId = 4
                        },
                        new
                        {
                            MissionId = 2,
                            ScientistEmployeeId = 3
                        });
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.Astronaut", b =>
                {
                    b.HasBaseType("AarhusSpaceProgram.Api.Entities.Employee");

                    b.Property<int>("HoursInSimulation")
                        .HasColumnType("int")
                        .HasColumnName("hours_in_sim");

                    b.Property<int>("HoursInSpace")
                        .HasColumnType("int")
                        .HasColumnName("hours_in_space");

                    b.Property<string>("Paygrade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("paygrade");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("rank");

                    b.ToTable("Astronaut");

                    b.HasData(
                        new
                        {
                            EmployeeId = 5,
                            HireDate = new DateOnly(2002, 1, 1),
                            Name = "Ron Weasley",
                            HoursInSimulation = 600,
                            HoursInSpace = 200,
                            Paygrade = "0-8",
                            Rank = "Commander"
                        },
                        new
                        {
                            EmployeeId = 6,
                            HireDate = new DateOnly(2003, 1, 1),
                            Name = "Neville Longbottom",
                            HoursInSimulation = 500,
                            HoursInSpace = 150,
                            Paygrade = "0-7",
                            Rank = "Pilot"
                        },
                        new
                        {
                            EmployeeId = 7,
                            HireDate = new DateOnly(2004, 1, 1),
                            Name = "Draco Malfoy",
                            HoursInSimulation = 550,
                            HoursInSpace = 100,
                            Paygrade = "0-7",
                            Rank = "Pilot"
                        });
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.Manager", b =>
                {
                    b.HasBaseType("AarhusSpaceProgram.Api.Entities.Employee");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("department");

                    b.ToTable("Manager");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            HireDate = new DateOnly(2001, 1, 1),
                            Name = "Dumbledore",
                            Department = "Flight control"
                        },
                        new
                        {
                            EmployeeId = 2,
                            HireDate = new DateOnly(2002, 1, 1),
                            Name = "Voldemord",
                            Department = "Engineering"
                        });
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.Scientist", b =>
                {
                    b.HasBaseType("AarhusSpaceProgram.Api.Entities.Employee");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("speciality");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title");

                    b.ToTable("Scientist");

                    b.HasData(
                        new
                        {
                            EmployeeId = 3,
                            HireDate = new DateOnly(2004, 2, 5),
                            Name = "Hermoine Granger",
                            Speciality = "Mars",
                            Title = "Astronomer"
                        },
                        new
                        {
                            EmployeeId = 4,
                            HireDate = new DateOnly(2004, 1, 1),
                            Name = "Harry Potter",
                            Speciality = "Alien life",
                            Title = "Alien investigator"
                        });
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.CelestialBody", b =>
                {
                    b.HasOne("AarhusSpaceProgram.Api.Entities.CelestialBody", "ParentBody")
                        .WithMany()
                        .HasForeignKey("ParentBodyId");

                    b.Navigation("ParentBody");
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.Mission", b =>
                {
                    b.HasOne("AarhusSpaceProgram.Api.Entities.LaunchPad", "LaunchPad")
                        .WithMany("Missions")
                        .HasForeignKey("LaunchPadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AarhusSpaceProgram.Api.Entities.Manager", "Manager")
                        .WithMany("ManagedMissions")
                        .HasForeignKey("ManagerId");

                    b.HasOne("AarhusSpaceProgram.Api.Entities.Rocket", "Rocket")
                        .WithOne("Mission")
                        .HasForeignKey("AarhusSpaceProgram.Api.Entities.Mission", "RocketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AarhusSpaceProgram.Api.Entities.CelestialBody", "TargetBody")
                        .WithMany("TargetMissions")
                        .HasForeignKey("TargetBodyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LaunchPad");

                    b.Navigation("Manager");

                    b.Navigation("Rocket");

                    b.Navigation("TargetBody");
                });

            modelBuilder.Entity("Mission_Astronaut", b =>
                {
                    b.HasOne("AarhusSpaceProgram.Api.Entities.Astronaut", null)
                        .WithMany()
                        .HasForeignKey("AstronautEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AarhusSpaceProgram.Api.Entities.Mission", null)
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Mission_Scientist", b =>
                {
                    b.HasOne("AarhusSpaceProgram.Api.Entities.Mission", null)
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AarhusSpaceProgram.Api.Entities.Scientist", null)
                        .WithMany()
                        .HasForeignKey("ScientistEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.Astronaut", b =>
                {
                    b.HasOne("AarhusSpaceProgram.Api.Entities.Employee", null)
                        .WithOne()
                        .HasForeignKey("AarhusSpaceProgram.Api.Entities.Astronaut", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.Manager", b =>
                {
                    b.HasOne("AarhusSpaceProgram.Api.Entities.Employee", null)
                        .WithOne()
                        .HasForeignKey("AarhusSpaceProgram.Api.Entities.Manager", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.Scientist", b =>
                {
                    b.HasOne("AarhusSpaceProgram.Api.Entities.Employee", null)
                        .WithOne()
                        .HasForeignKey("AarhusSpaceProgram.Api.Entities.Scientist", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.CelestialBody", b =>
                {
                    b.Navigation("TargetMissions");
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.LaunchPad", b =>
                {
                    b.Navigation("Missions");
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.Rocket", b =>
                {
                    b.Navigation("Mission");
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Entities.Manager", b =>
                {
                    b.Navigation("ManagedMissions");
                });
#pragma warning restore 612, 618
        }
    }
}
